# $FreeBSD: src/lib/clang/libllvmx86info/Makefile,v 1.3 2010/09/19 10:54:58 dim Exp $

LIB=	llvmx86info

SRCDIR=	lib/Target/X86/TargetInfo/
INCDIR=	lib/Target/X86
SRCS=	X86TargetInfo.cpp

TGHDRS=	X86GenInstrNames \
	X86GenRegisterNames

.include "../clang.lib.mk"
