# $FreeBSD: src/lib/clang/libllvmx86info/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmx86info

SRCDIR=	lib/Target/X86/TargetInfo/
INCDIR=	lib/Target/X86
SRCS=	X86TargetInfo.cpp

TGHDRS= X86GenRegisterNames X86GenInstrNames

.include "../clang.lib.mk"
