# $FreeBSD: src/lib/clang/libllvmx86info/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	llvmx86info

SRCDIR=	lib/Target/X86/TargetInfo/
INCDIR=	lib/Target/X86
SRCS=	X86TargetInfo.cpp

TGHDRS= X86GenInstrNames \
	X86GenRegisterNames

.include "../clang.lib.mk"
