# $FreeBSD: src/lib/clang/include/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

.PATH: ${.CURDIR}/../../../contrib/llvm/tools/clang/lib/Headers

INCSDIR=${INCLUDEDIR}/clang/2.0

INCS=	emmintrin.h mm_malloc.h mmintrin.h pmmintrin.h tmmintrin.h xmmintrin.h

.include <bsd.init.mk>
.include <bsd.incs.mk>
.include <bsd.obj.mk>
