# $FreeBSD: src/lib/clang/include/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

.PATH: ${.CURDIR}/../../../contrib/llvm/tools/clang/lib/Headers

INCSDIR=${INCLUDEDIR}/clang/2.8

INCS=	emmintrin.h \
	mm_malloc.h \
	mmintrin.h \
	pmmintrin.h \
	tmmintrin.h \
	xmmintrin.h

.include <bsd.init.mk>
.include <bsd.incs.mk>
.include <bsd.obj.mk>
