# $FreeBSD: src/lib/clang/libclanganalysis/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	clanganalysis

SRCDIR=	tools/clang/lib/Analysis
SRCS=	AnalysisContext.cpp CFG.cpp LiveVariables.cpp \
	PrintfFormatString.cpp ReachableCode.cpp \
	UninitializedValues.cpp

TGHDRS=	DiagnosticAnalysisKinds DiagnosticCommonKinds StmtNodes

.include "../clang.lib.mk"
