# $FreeBSD: src/lib/libproc/Makefile,v 1.4 2010/02/25 22:16:30 ru Exp $

LIB=	proc

SRCS=				\
	proc_create.c		\
	proc_sym.c		\
	proc_util.c

INCS=	libproc.h

CFLAGS+=	-I${.CURDIR}

SHLIB_MAJOR=	2

WITHOUT_MAN=

.include <bsd.lib.mk>
