#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/sbin/tunefs/Makefile,v 1.11 2010/04/24 07:59:45 jeff Exp $

PROG=	tunefs
DPADD=	${LIBUFS}
LDADD=	-lufs
MAN=	tunefs.8

WARNS=	3

.include <bsd.prog.mk>
