# $FreeBSD: src/sys/modules/cc/cc_vegas/Makefile,v 1.1 2011/02/01 06:17:00 lstewart Exp $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/../../../netinet/cc
KMOD=	cc_vegas
SRCS=	cc_vegas.c

.include <bsd.kmod.mk>
