# $FreeBSD: src/sys/modules/aha/Makefile,v 1.11 2011/01/06 21:04:00 imp Exp $

.PATH: ${.CURDIR}/../../dev/aha

KMOD=	aha
SRCS=	aha.c aha_isa.c ahareg.h opt_cam.h device_if.h bus_if.h \
	isa_if.h

.include <bsd.kmod.mk>
