# $FreeBSD: src/usr.sbin/pkg_install/info/Makefile,v 1.22 2010/04/23 11:07:43 flz Exp $

PROG=	pkg_info
SRCS=	main.c perform.c show.c

WFORMAT?=	1

DPADD=	${LIBMD}
LDADD=	-lmd

.include <bsd.prog.mk>
