#       $NetBSD: Makefile,v 1.3 2009/04/14 22:15:26 lukem Exp $
# $FreeBSD: src/usr.bin/seq/Makefile,v 1.1 2010/02/19 23:54:12 delphij Exp $

PROG=	seq
DPADD=	${LIBM}
LDADD=	-lm

.include <bsd.prog.mk>
