# $FreeBSD: src/lib/clang/libclangrewrite/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	clangrewrite

SRCDIR=	tools/clang/lib/Rewrite
SRCS=	DeltaTree.cpp HTMLRewrite.cpp RewriteRope.cpp Rewriter.cpp \
	TokenRewriter.cpp

TGHDRS=	DiagnosticCommonKinds StmtNodes

.include "../clang.lib.mk"
