# $FreeBSD: src/share/doc/legal/intel_iwn/Makefile,v 1.1 2010/05/27 08:21:52 rpaulo Exp $

NO_OBJ=
FILES=		${.CURDIR}/../../../../sys/contrib/dev/iwn/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal/intel_iwn

.include <bsd.prog.mk>
