# $FreeBSD: src/usr.sbin/moused/Makefile,v 1.13 2010/01/02 11:07:44 ed Exp $

PROG=	moused
MAN=	moused.8

DPADD=	${LIBUTIL}  ${LIBM}
LDADD=	-lutil -lm

#BINMODE=4555
#PRECIOUSPROG=

.include <bsd.prog.mk>
