# $FreeBSD: src/usr.sbin/pkg_install/add/Makefile,v 1.22 2010/04/23 11:07:43 flz Exp $

.include <bsd.own.mk>

PROG=	pkg_add
SRCS=	main.c perform.c futil.c extract.c

WARNS?=	3
WFORMAT?=	1

.include <bsd.prog.mk>
