# $FreeBSD: src/lib/clang/libllvmmipsinfo/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	llvmmipsinfo

SRCDIR=	lib/Target/Mips/TargetInfo/
INCDIR=	lib/Target/Mips
SRCS=	MipsTargetInfo.cpp

TGHDRS= MipsGenRegisterNames \
	MipsGenInstrNames

.include "../clang.lib.mk"
