# $FreeBSD: src/lib/clang/libllvmmipsinfo/Makefile,v 1.3 2010/09/19 10:54:58 dim Exp $

LIB=	llvmmipsinfo

SRCDIR=	lib/Target/Mips/TargetInfo/
INCDIR=	lib/Target/Mips
SRCS=	MipsTargetInfo.cpp

TGHDRS=	MipsGenRegisterNames \
	MipsGenInstrNames

.include "../clang.lib.mk"
