# $FreeBSD: src/lib/clang/libllvmmipsinfo/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmmipsinfo

SRCDIR=	lib/Target/Mips/TargetInfo/
INCDIR=	lib/Target/Mips
SRCS=	MipsTargetInfo.cpp

TGHDRS= MipsGenRegisterNames MipsGenInstrNames

.include "../clang.lib.mk"
