# $FreeBSD: src/lib/clang/libllvmpowerpcasmprinter/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	llvmpowerpcasmprinter

SRCDIR=	lib/Target/PowerPC/AsmPrinter
INCDIR=	lib/Target/PowerPC
SRCS=	PPCAsmPrinter.cpp

TGHDRS=	PPCGenAsmWriter \
	PPCGenInstrNames \
	PPCGenRegisterInfo.h \
	PPCGenRegisterNames

.include "../clang.lib.mk"
