# $FreeBSD: src/lib/clang/libllvmpowerpcasmprinter/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmpowerpcasmprinter

SRCDIR=	lib/Target/PowerPC/AsmPrinter
INCDIR=	lib/Target/PowerPC
SRCS=	PPCAsmPrinter.cpp

TGHDRS=	PPCGenAsmWriter PPCGenInstrNames PPCGenRegisterInfo.h \
	PPCGenRegisterNames

.include "../clang.lib.mk"
