#	$FreeBSD: src/libexec/tftp-proxy/Makefile,v 1.2 2010/01/02 09:50:19 ed Exp $

.PATH:	${.CURDIR}/../../contrib/pf/tftp-proxy

PROG=	tftp-proxy
SRCS=	tftp-proxy.c filter.c
MAN=	tftp-proxy.8

WARNS?=	3

.include <bsd.prog.mk>
