# $FreeBSD: src/usr.sbin/pc-sysinstall/backend-partmanager/Makefile,v 1.1 2010/06/24 22:21:47 imp Exp $

FILES=	create-part.sh delete-part.sh

FILESDIR=${SHAREDIR}/pc-sysinstall/backend-partmanager
NO_OBJ=

.include <bsd.prog.mk>
