# $FreeBSD: src/gnu/usr.bin/cc/Makefile.tgt,v 1.15 2010/07/10 02:29:22 nwhitehorn Exp $

TARGET_ARCH?=	${MACHINE_ARCH}

.if ${TARGET_ARCH} == "amd64"
GCC_CPU=	i386
.elif ${TARGET_ARCH} == "powerpc" || ${TARGET_ARCH} == "powerpc64"
GCC_CPU=	rs6000
.elif ${TARGET_ARCH} == "sparc64"
GCC_CPU=	sparc
.else
GCC_CPU=	${TARGET_ARCH}
.endif

.if ${TARGET_ARCH} == "ia64"
TARGET_CPU_DEFAULT= MASK_GNU_AS|MASK_GNU_LD
.endif
.if ${TARGET_ARCH} == "sparc64"
TARGET_CPU_DEFAULT= TARGET_CPU_ultrasparc
.endif
.if ${TARGET_ARCH} == "powerpc64"
TARGET_CPU_DEFAULT= \"powerpc64\"
.endif

