# $FreeBSD: src/sys/modules/cc/cc_htcp/Makefile,v 1.1 2010/12/02 06:40:21 lstewart Exp $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/../../../netinet/cc
KMOD=	cc_htcp
SRCS=	cc_htcp.c

.include <bsd.kmod.mk>
