#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.sbin/chown/Makefile,v 1.13 2010/01/02 11:07:44 ed Exp $

PROG=	chown
LINKS=	${BINDIR}/chown /usr/bin/chgrp
MAN=	chgrp.1 chown.8

.include <bsd.prog.mk>
