#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/smm/03.fsck/Makefile,v 1.6 2010/12/04 10:11:20 uqs Exp $

VOLUME=	smm/03.fsck
SRCS=	0.t 1.t 2.t 3.t 4.t
MACROS=	-ms

.include <bsd.doc.mk>
