#
# $FreeBSD: src/tools/regression/sockets/unix_seqpacket_exercise/Makefile,v 1.1 2009/10/05 15:27:01 rwatson Exp $
#

PROG=unix_seqpacket_exercise
CFLAGS+=-Wall -Werror
NO_MAN=

.include <bsd.prog.mk>
