# $FreeBSD: src/sys/modules/khelp/h_ertt/Makefile,v 1.1 2011/01/24 23:08:38 lstewart Exp $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/../../../netinet/khelp
KMOD=	h_ertt
SRCS=	h_ertt.c

.include <bsd.kmod.mk>
