#
# $FreeBSD: src/tools/regression/netipx/ipxdgramloopback/Makefile,v 1.3 2010/02/25 14:42:26 ru Exp $
#

PROG=	ipxdgramloopback
NO_MAN=

DPADD=	${LIBIPX}
LDADD=	-lipx
WARNS?=	3

.include <bsd.prog.mk>
