# $FreeBSD: src/lib/clang/libllvmsystem/Makefile,v 1.2 2010/06/15 17:08:03 ed Exp $

LIB=	llvmsystem

SRCDIR=	lib/System
SRCS=	Atomic.cpp DynamicLibrary.cpp Errno.cpp Host.cpp Memory.cpp \
	Mutex.cpp Path.cpp Process.cpp Program.cpp RWMutex.cpp \
	SearchForAddressOfSpecialSymbol.cpp Signals.cpp \
	ThreadLocal.cpp Threading.cpp TimeValue.cpp Valgrind.cpp

.include "../clang.lib.mk"
