# $FreeBSD: src/lib/clang/libllvmsystem/Makefile,v 1.4 2010/07/22 19:09:34 rpaulo Exp $

LIB=	llvmsystem

SRCDIR=	lib/System
SRCS=	Alarm.cpp \
	Atomic.cpp \
	Disassembler.cpp \
	DynamicLibrary.cpp \
	Errno.cpp \
	Host.cpp \
	IncludeFile.cpp \
	Memory.cpp \
	Mutex.cpp \
	Path.cpp \
	Process.cpp \
	Program.cpp \
	RWMutex.cpp \
	SearchForAddressOfSpecialSymbol.cpp \
	Signals.cpp \
	ThreadLocal.cpp \
	Threading.cpp \
	TimeValue.cpp \
	Valgrind.cpp
LLVM_REQUIRES_RTTI=

.include "../clang.lib.mk"
