# $FreeBSD: src/lib/clang/libllvmsystem/Makefile,v 1.5 2010/09/20 16:43:17 dim Exp $

LIB=	llvmsystem

SRCDIR=	lib/System
SRCS=	Atomic.cpp \
	DynamicLibrary.cpp \
	Errno.cpp \
	Host.cpp \
	Memory.cpp \
	Mutex.cpp \
	Path.cpp \
	Process.cpp \
	Program.cpp \
	RWMutex.cpp \
	SearchForAddressOfSpecialSymbol.cpp \
	Signals.cpp \
	ThreadLocal.cpp \
	Threading.cpp \
	TimeValue.cpp \
	Valgrind.cpp
LLVM_REQUIRES_RTTI=

.include "../clang.lib.mk"
