# $FreeBSD: src/sys/modules/cc/cc_cubic/Makefile,v 1.1 2010/12/02 06:05:44 lstewart Exp $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/../../../netinet/cc
KMOD=	cc_cubic
SRCS=	cc_cubic.c

.include <bsd.kmod.mk>
