# $FreeBSD: src/lib/clang/libllvmipa/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	llvmipa

SRCDIR=	lib/Analysis/IPA
SRCS=	CallGraph.cpp \
	CallGraphSCCPass.cpp \
	FindUsedTypes.cpp \
	GlobalsModRef.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
