# $FreeBSD: src/lib/clang/libllvmipa/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmipa

SRCDIR=	lib/Analysis/IPA
SRCS=	CallGraph.cpp CallGraphSCCPass.cpp FindUsedTypes.cpp \
	GlobalsModRef.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
