# $FreeBSD: src/share/examples/pf/Makefile,v 1.4 2007/11/11 01:16:51 mlaier Exp $

NO_OBJ=

FILES=	faq-example1 faq-example2 faq-example3 \
	ackpri queue1 queue2 queue3 queue4 \
	pf.conf \
	spamd

FILESDIR=	${SHAREDIR}/examples/pf

.include <bsd.prog.mk>
