#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/bootparams,v 1.8 2007/12/08 07:20:22 dougb Exp $
#

# PROVIDE: bootparams
# REQUIRE: rpcbind DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="bootparamd"
rcvar=`set_rcvar`
required_files="/etc/bootparams"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
