#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/bsnmpd,v 1.2 2008/07/16 19:50:29 dougb Exp $
#

# PROVIDE: bsnmpd
# REQUIRE: NETWORKING syslogd
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="bsnmpd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/snmpd.pid"

load_rc_config $name
run_rc_command "$1"
