#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/DAEMON,v 1.6 2007/12/08 07:20:22 dougb Exp $
#

# PROVIDE: DAEMON
# REQUIRE: NETWORKING SERVERS

#	This is a dummy dependency, to ensure that general purpose daemons
#	are run _after_ the above are.
