#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/ftp-proxy,v 1.3 2008/07/16 19:50:29 dougb Exp $
#

# PROVIDE: ftp-proxy
# REQUIRE: DAEMON pf
# KEYWORD: shutdown

. /etc/rc.subr

name="ftpproxy"
rcvar=`set_rcvar`
command="/usr/sbin/ftp-proxy"

load_rc_config $name
run_rc_command "$1"
