#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/gssd,v 1.1 2008/11/03 10:38:00 dfr Exp $
#

# PROVIDE: gssd
# REQUIRE: root
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="gssd"

load_rc_config $name
rcvar="gssd_enable"
command="${gssd:-/usr/sbin/${name}}"
eval ${name}_flags=\"${gssd_flags}\"
run_rc_command "$1"
