#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/kerberos,v 1.8 2008/01/25 05:23:01 mtm Exp $
#

# PROVIDE: kerberos
# REQUIRE: NETWORKING

. /etc/rc.subr

name="kerberos5"
rcvar="kerberos5_server_enable"

load_rc_config $name
command="${kerberos5_server}"
kerberos5_flags="${kerberos5_server_flags}"
run_rc_command "$1"
