#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/LOGIN,v 1.6 2007/12/08 07:20:22 dougb Exp $
#

# PROVIDE: LOGIN
# REQUIRE: DAEMON

#	This is a dummy dependency to ensure user services such as xdm,
#	inetd, cron and kerberos are started after everything else, in case
#	the administrator has increased the system security level and
#	wants to delay user logins until the system is (almost) fully
#	operational.
