#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/mroute6d,v 1.5 2009/09/12 22:13:41 hrs Exp $
#

# PROVIDE: mroute6d
# REQUIRE: netif routing
# BEFORE: NETWORKING
# KEYWORD: nojail

. /etc/rc.subr

name="mroute6d"
rcvar=`set_rcvar`
command="/usr/local/sbin/pim6dd"

load_rc_config $name
run_rc_command "$1"
