#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/nfsuserd,v 1.1 2009/06/02 22:15:47 rmacklem Exp $
#

# PROVIDE: nfsuserd
# REQUIRE: NETWORKING
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="nfsuserd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
sig_stop="USR1"

load_rc_config $name

run_rc_command "$1"
