#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/rarpd,v 1.7 2007/12/08 07:20:22 dougb Exp $
#

# PROVIDE: rarpd
# REQUIRE: DAEMON cleanvar
# BEFORE:  LOGIN
# KEYWORD: nojail

. /etc/rc.subr

name="rarpd"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
required_files="/etc/ethers"

load_rc_config $name
run_rc_command "$1"
