#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/route6d,v 1.11 2009/09/12 22:19:48 hrs Exp $
#

# PROVIDE: route6d
# REQUIRE: netif routing
# KEYWORD: nojail

. /etc/rc.subr

name="route6d"
rcvar=`set_rcvar`

set_rcvar_obsolete ipv6_router_enable route6d_enable
set_rcvar_obsolete ipv6_router route6d_program
set_rcvar_obsolete ipv6_router_flags route6d_flags

load_rc_config $name
run_rc_command "$1"
