#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/routed,v 1.14 2009/09/12 22:19:48 hrs Exp $
#

# PROVIDE: routed
# REQUIRE: netif routing
# KEYWORD: nojail

. /etc/rc.subr

name="routed"
desc="network RIP and router discovery routing daemon"
rcvar=`set_rcvar`

set_rcvar_obsolete router_enable routed_enable
set_rcvar_obsolete router routed_program
set_rcvar_obsolete router_flags	routed_flags

load_rc_config $name
run_rc_command "$1"
