#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/rpcbind,v 1.15 2011/01/31 21:03:08 dougb Exp $
#

# PROVIDE: rpcbind
# REQUIRE: NETWORKING ntpdate syslogd named
# KEYWORD: shutdown

. /etc/rc.subr

name="rpcbind"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

stop_postcmd='/bin/rm -f /var/run/rpcbind.*'

load_rc_config $name
run_rc_command "$1"
