#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/rtsold,v 1.5 2010/02/27 19:02:21 ume Exp $
#

# PROVIDE: rtsold
# REQUIRE: netif
# BEFORE: NETWORKING
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="rtsold"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"
pidfile="/var/run/${name}.pid"
start_postcmd="rtsold_poststart"

rtsold_poststart()
{
	# wait for DAD
	sleep $(($(${SYSCTL_N} net.inet6.ip6.dad_count) + 1))
}

load_rc_config $name
run_rc_command "$1"
