#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/rwho,v 1.6 2008/07/16 19:50:29 dougb Exp $
#

# PROVIDE: rwho
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="rwhod"
rcvar="`set_rcvar`"
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
