#!/bin/sh
#
# $FreeBSD: src/etc/rc.d/timed,v 1.7 2008/07/16 19:50:29 dougb Exp $
#

# PROVIDE: timed
# REQUIRE: DAEMON
# BEFORE:  LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="timed"
rcvar=`set_rcvar`
command="/usr/sbin/${name}"

load_rc_config $name
run_rc_command "$1"
