# $FreeBSD: src/lib/clang/libclangindex/Makefile,v 1.1 2010/09/20 16:43:17 dim Exp $

LIB=	clangindex

SRCDIR=	tools/clang/lib/Index
SRCS=	ASTLocation.cpp \
	Analyzer.cpp \
	CallGraph.cpp \
	DeclReferenceMap.cpp \
	Entity.cpp \
	GlobalSelector.cpp \
	Handlers.cpp \
	IndexProvider.cpp \
	Indexer.cpp \
	Program.cpp \
	SelectorMap.cpp \

TGHDRS=	AttrList \
	Attrs \
	DeclNodes \
	DiagnosticCommonKinds \
	StmtNodes

.include "../clang.lib.mk"
