#	@(#)Makefile	1.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/ktrace/Makefile,v 1.7 2010/01/02 10:27:05 ed Exp $

PROG=	ktrace
SRCS=	ktrace.c subr.c
MLINKS= ktrace.1 trace.1 

WARNS?=	4

.include <bsd.prog.mk>
