# $Id$
# $FreeBSD: src/usr.sbin/bluetooth/Makefile,v 1.9 2010/11/12 19:43:12 emax Exp $

SUBDIR= \
	ath3kfw \
	bcmfw \
	bt3cfw \
	bthidcontrol \
	bthidd \
	btpand \
	hccontrol \
	hcsecd \
	hcseriald \
	l2control \
	l2ping \
	rfcomm_pppd \
	sdpcontrol \
	sdpd

.include <bsd.subdir.mk>

