# $Id$
# $FreeBSD: src/usr.sbin/bluetooth/Makefile,v 1.8 2009/02/02 18:10:51 emax Exp $

SUBDIR= \
	bcmfw \
	bt3cfw \
	bthidcontrol \
	bthidd \
	btpand \
	hccontrol \
	hcsecd \
	hcseriald \
	l2control \
	l2ping \
	rfcomm_pppd \
	sdpcontrol \
	sdpd

.include <bsd.subdir.mk>

