#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/uudecode/Makefile,v 1.9 2010/01/02 10:27:05 ed Exp $

PROG=	uudecode
LINKS=	${BINDIR}/uudecode ${BINDIR}/b64decode
NO_MAN=

.include <bsd.prog.mk>
