# $FreeBSD: src/lib/clang/libllvmasmparser/Makefile,v 1.1 2010/07/20 17:16:57 ed Exp $

LIB=	llvmasmparser

SRCDIR=	lib/AsmParser
SRCS=	LLLexer.cpp \
	LLParser.cpp \
	Parser.cpp

.include "../clang.lib.mk"
