# $FreeBSD: src/usr.sbin/ctm/ctm_dequeue/Makefile,v 1.6 2010/01/02 11:07:44 ed Exp $

.PATH: ${.CURDIR}/../ctm_rmail

PROG=	ctm_dequeue
NO_MAN=
SRCS=	ctm_dequeue.c error.c

CFLAGS+= -I${.CURDIR}/../ctm_rmail

WARNS?=	1

.include <bsd.prog.mk>
