# $FreeBSD: src/usr.sbin/ctm/ctm_rmail/Makefile,v 1.9 2010/01/02 11:07:44 ed Exp $

PROG=	ctm_rmail
MLINKS=	ctm_rmail.1 ctm_smail.1 \
	ctm_rmail.1 ctm_dequeue.1
SRCS=	ctm_rmail.c error.c

WARNS?=	2

.include <bsd.prog.mk>
