# $FreeBSD: src/libexec/rpc.rwalld/Makefile,v 1.8 2010/01/02 09:50:19 ed Exp $

PROG =	rpc.rwalld
SRCS =	rwalld.c
MAN =	rpc.rwalld.8

DPADD=	${LIBUTIL}
LDADD=	-lutil

WARNS?=	2

.include <bsd.prog.mk>
