# Make `routed` tools for BSD/OS
# $Revision: 1.6 $
# $FreeBSD: src/sbin/routed/rtquery/Makefile,v 1.15 2010/02/27 10:17:27 uqs Exp $

PROG=	rtquery
MAN=	rtquery.8
LDADD=	-lmd
DPADD=	${LIBMD}
WARNS?=	3

.include <bsd.prog.mk>
