# $FreeBSD: src/lib/clang/Makefile,v 1.3 2010/09/20 16:43:17 dim Exp $

SUBDIR=	libclanganalysis \
	libclangast \
	libclangbasic \
	libclangchecker \
	libclangcodegen \
	libclangdriver \
	libclangindex \
	libclangfrontend \
	libclangfrontendtool \
	libclanglex \
	libclangparse \
	libclangrewrite \
	libclangsema \
	libclangserialization \
	\
	libllvmanalysis \
	libllvmasmparser \
	libllvmasmprinter \
	libllvmbitreader \
	libllvmbitwriter \
	libllvmcodegen \
	libllvminstcombine \
	libllvmcore \
	libllvmipa \
	libllvmipo \
	libllvmmc \
	libllvmmcparser \
	libllvmscalaropts \
	libllvmselectiondag \
	libllvmsupport \
	libllvmsystem \
	libllvmtarget \
	libllvmtransformutils \
	\
	libllvmarmasmparser \
	libllvmarmasmprinter \
	libllvmarmcodegen \
	libllvmarminfo \
	libllvmmipsasmprinter \
	libllvmmipscodegen \
	libllvmmipsinfo \
	libllvmpowerpcasmprinter \
	libllvmpowerpccodegen \
	libllvmpowerpcinfo \
	libllvmx86asmparser \
	libllvmx86asmprinter \
	libllvmx86codegen \
	libllvmx86disassembler \
	libllvmx86info \
	\
	include

.include <bsd.subdir.mk>
