# $FreeBSD: src/lib/clang/libllvmx86asmprinter/Makefile,v 1.3 2010/09/20 16:43:17 dim Exp $

LIB=	llvmx86asmprinter

SRCDIR=	lib/Target/X86/AsmPrinter
INCDIR=	lib/Target/X86
SRCS=	X86ATTInstPrinter.cpp \
	X86InstComments.cpp \
	X86IntelInstPrinter.cpp

TGHDRS=	X86GenAsmWriter \
	X86GenAsmWriter1 \
	X86GenInstrNames

.include "../clang.lib.mk"
