# $FreeBSD: src/usr.sbin/Makefile.mips,v 1.3 2011/01/27 14:16:12 jchandra Exp $

SUBDIR:=	${SUBDIR:Nsysinstall}
# uathload broken for n32 and n64 due to toolchain issues
.if ${MACHINE_ARCH:Mmipse[lb]} == ""
SUBDIR:=	${SUBDIR:Nuathload}
.endif
