# $FreeBSD: src/lib/clang/libllvmmcparser/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	llvmmcparser

SRCDIR=	lib/MC/MCParser
SRCS=	AsmLexer.cpp \
	AsmParser.cpp \
	DarwinAsmParser.cpp \
	ELFAsmParser.cpp \
	MCAsmLexer.cpp \
	MCAsmParser.cpp \
	MCAsmParserExtension.cpp \
	TargetAsmParser.cpp

.include "../clang.lib.mk"
