# $FreeBSD: src/lib/clang/libllvmmcparser/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmmcparser

SRCDIR=	lib/MC/MCParser
SRCS=	AsmLexer.cpp AsmParser.cpp MCAsmLexer.cpp MCAsmParser.cpp \
	TargetAsmParser.cpp

.include "../clang.lib.mk"
