#
# $FreeBSD: src/usr.sbin/bsnmpd/tools/libbsnmptools/Makefile,v 1.2 2010/12/11 13:24:01 syrinx Exp $
#

.PATH: ${.CURDIR}

LIB=	bsnmptools
#INTERNALLIB=
SRCS=	bsnmpimport.c bsnmpmap.c bsnmptools.c bsnmptc.c

SHLIB_MAJOR=	0

.include <bsd.lib.mk>
