# $FreeBSD: src/lib/clang/libllvmarmasmprinter/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmarmasmprinter

SRCDIR=	lib/Target/ARM/AsmPrinter
INCDIR=	lib/Target/ARM
SRCS=	ARMAsmPrinter.cpp ARMInstPrinter.cpp ARMMCInstLower.cpp

TGHDRS=	ARMGenAsmWriter ARMGenInstrNames ARMGenRegisterInfo.h \
	ARMGenRegisterNames

.include "../clang.lib.mk"
