# $FreeBSD: src/lib/clang/libllvmarmasmprinter/Makefile,v 1.3 2010/09/20 16:43:17 dim Exp $

LIB=	llvmarmasmprinter

SRCDIR=	lib/Target/ARM/AsmPrinter
INCDIR=	lib/Target/ARM
SRCS=	ARMInstPrinter.cpp

TGHDRS=	ARMGenAsmWriter \
	ARMGenInstrNames \
	ARMGenRegisterNames

.include "../clang.lib.mk"
