#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/lock/Makefile,v 1.11 2010/06/28 08:30:10 gavin Exp $

PROG=	lock
BINOWN=	root
BINMODE=4555
DPADD=	${LIBCRYPT}
LDADD=	-lcrypt

.include <bsd.prog.mk>
