# $FreeBSD: src/lib/librtld_db/Makefile,v 1.1 2010/07/31 14:26:10 rpaulo Exp $

.include <bsd.own.mk>

LIB=		rtld_db
SHLIB_MAJOR= 	1
MAN=		librtld_db.3

SRCS=		rtld_db.c
INCS=		rtld_db.h

CFLAGS+= -I${.CURDIR}

.include <bsd.lib.mk>
