#	from: @(#)Makefile	5.2 (Berkeley) 5/11/90
# $FreeBSD: src/usr.bin/rpcinfo/Makefile,v 1.9 2010/01/02 10:27:05 ed Exp $

PROG=	rpcinfo
SRCS=	rpcinfo.c
MAN=	rpcinfo.8

CFLAGS+= -DPORTMAP

WARNS?=	2

.include <bsd.prog.mk>
