# Cronyx Id: sbin.sconfig.Makefile,v 1.1.4.1 2003/02/17 12:51:24 rik Exp $
# $FreeBSD: src/sbin/sconfig/Makefile,v 1.4 2009/10/19 16:00:24 ru Exp $

PROG=	sconfig
MAN=	sconfig.8
MANSUBDIR= /i386
WARNS?=	2

.include <bsd.prog.mk>
