# $FreeBSD: src/lib/clang/libllvmsupport/Makefile,v 1.3 2010/06/15 17:28:16 ed Exp $

LIB=	llvmsupport

SRCDIR=	lib/Support
SRCS=	APFloat.cpp APInt.cpp APSInt.cpp Allocator.cpp CommandLine.cpp \
	ConstantRange.cpp Debug.cpp DeltaAlgorithm.cpp Dwarf.cpp \
	ErrorHandling.cpp FileUtilities.cpp FoldingSet.cpp \
	FormattedStream.cpp GraphWriter.cpp ManagedStatic.cpp \
	MemoryBuffer.cpp PluginLoader.cpp PrettyStackTrace.cpp \
	Regex.cpp SlowOperationInformer.cpp SmallPtrSet.cpp \
	SmallVector.cpp SourceMgr.cpp Statistic.cpp StringExtras.cpp \
	StringMap.cpp StringPool.cpp StringRef.cpp TargetRegistry.cpp \
	Timer.cpp Triple.cpp Twine.cpp circular_raw_ostream.cpp \
	raw_os_ostream.cpp raw_ostream.cpp regcomp.c regerror.c \
	regexec.c regfree.c regstrlcpy.c

.include "../clang.lib.mk"
