# $FreeBSD: src/lib/clang/libclangfrontendtool/Makefile,v 1.1 2010/09/20 16:43:17 dim Exp $

LIB=	clangfrontendtool

SRCDIR=	tools/clang/lib/FrontendTool
SRCS=	ExecuteCompilerInvocation.cpp

TGHDRS=	CC1Options \
	DiagnosticCommonKinds \
	DiagnosticFrontendKinds

.include "../clang.lib.mk"
