# $FreeBSD: src/lib/clang/libllvmpowerpcinfo/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	llvmpowerpcinfo

SRCDIR=	lib/Target/PowerPC/TargetInfo/
INCDIR=	lib/Target/PowerPC
SRCS=	PowerPCTargetInfo.cpp

TGHDRS= PPCGenRegisterNames \
	PPCGenInstrNames

.include "../clang.lib.mk"
