# $FreeBSD: src/lib/clang/libllvmpowerpcinfo/Makefile,v 1.3 2010/09/19 10:54:58 dim Exp $

LIB=	llvmpowerpcinfo

SRCDIR=	lib/Target/PowerPC/TargetInfo/
INCDIR=	lib/Target/PowerPC
SRCS=	PowerPCTargetInfo.cpp

TGHDRS=	PPCGenRegisterNames \
	PPCGenInstrNames

.include "../clang.lib.mk"
