# $FreeBSD: src/lib/clang/libllvmpowerpcinfo/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmpowerpcinfo

SRCDIR=	lib/Target/PowerPC/TargetInfo/
INCDIR=	lib/Target/PowerPC
SRCS=	PowerPCTargetInfo.cpp

TGHDRS= PPCGenRegisterNames PPCGenInstrNames

.include "../clang.lib.mk"
