# $FreeBSD: src/tools/regression/usr.bin/Makefile,v 1.17 2010/03/14 10:24:03 edwin Exp $

SUBDIR=	apply calendar comm file2c join jot m4 ncal printf sed tr	\
	uudecode uuencode xargs
.if !defined(AUTOMATED)
SUBDIR+= lastcomm
.endif

.include <bsd.subdir.mk>
