#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/smm/11.timedop/Makefile,v 1.5 2010/12/04 10:11:20 uqs Exp $

VOLUME=	smm/11.timedop
SRCS=	timed.ms
MACROS=	-ms

.include <bsd.doc.mk>
