#	From: @(#)Makefile	8.1 (Berkeley) 8/14/93
# $FreeBSD: src/share/doc/psd/12.make/Makefile,v 1.8 2010/12/04 10:11:20 uqs Exp $

VOLUME=	psd/12.make
SRCS=	stubs tutorial.ms
MACROS=	-ms

.include <bsd.doc.mk>
