#	@(#)Makefile	8.4 (Berkeley) 6/22/95
# $FreeBSD: src/usr.sbin/rpc.umntall/Makefile,v 1.6 2010/01/02 11:07:44 ed Exp $

PROG=	rpc.umntall
MAN=	rpc.umntall.8
SRCS=	rpc.umntall.c mounttab.c

WARNS?= 3

.include <bsd.prog.mk>
