#	@(#)Makefile	8.1 (Berkeley) 6/5/93
#	$FreeBSD: src/usr.sbin/rip6query/Makefile,v 1.8 2010/01/02 11:07:44 ed Exp $

PROG=	rip6query
MAN=	rip6query.8

CFLAGS+= -I${.CURDIR}/../route6d

.include <bsd.prog.mk>
