#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/smm/12.timed/Makefile,v 1.8 2010/12/04 10:11:20 uqs Exp $

VOLUME=		smm/12.timed
SRCS=		timed.ms
EXTRA=		date loop time unused
MACROS=		-ms
USE_SOELIM=
USE_TBL=

.include <bsd.doc.mk>
