# $FreeBSD: src/tools/tools/ath/ath_ee_v4k_print/Makefile,v 1.1 2011/01/24 06:46:03 adrian Exp $

.PATH:  ${.CURDIR}/../../../../sys/dev/ath/ath_hal

PROG=	ath_ee_v4k_print
SRCS=	main.c eeprom.c v4k.c
NOMAN=	yes
NO_MAN=	yes

.include <../Makefile.inc>

.include <bsd.prog.mk>
