# $FreeBSD: src/lib/clang/libclangdriver/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	clangdriver

SRCDIR=	tools/clang/lib/Driver
SRCS=	Action.cpp Arg.cpp ArgList.cpp CC1AsOptions.cpp CC1Options.cpp \
	Compilation.cpp Driver.cpp DriverOptions.cpp HostInfo.cpp \
	Job.cpp OptTable.cpp Option.cpp Phases.cpp Tool.cpp \
	ToolChain.cpp ToolChains.cpp Tools.cpp Types.cpp

TGHDRS=	CC1AsOptions CC1Options DiagnosticCommonKinds \
	DiagnosticDriverKinds Options

.include "../clang.lib.mk"
