# $FreeBSD: src/sys/modules/cc/cc_chd/Makefile,v 1.1 2011/02/01 07:05:14 lstewart Exp $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/../../../netinet/cc
KMOD=	cc_chd
SRCS=	cc_chd.c

.include <bsd.kmod.mk>
