# $FreeBSD: src/tools/regression/kqueue/Makefile,v 1.2 2010/03/02 16:58:04 uqs Exp $
#
# svn://mark.heily.com/libkqueue/trunk/test
# Last update: r114
#
# libkqueue and test suite by Mark Heily <mark@heily.com>
#

PROG=kqtest
SRCS=			\
	main.c		\
	read.c		\
	timer.c		\
	vnode.c		\
	proc.c		\
	signal.c	\
	user.c
NO_MAN=
WARNS?=	2

.include "bsd.prog.mk"
