#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/sbin/shutdown/Makefile,v 1.10 2009/10/19 16:00:24 ru Exp $

PROG=	shutdown
MAN=	shutdown.8

BINOWN=	root
BINGRP=	operator
BINMODE=4550

.include <bsd.prog.mk>
