#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/sbin/shutdown/Makefile,v 1.11 2010/12/30 18:06:31 pjd Exp $

PROG=	shutdown
MAN=	shutdown.8
LINKS=	${BINDIR}/shutdown ${BINDIR}/poweroff
MLINKS=	shutdown.8 poweroff.8

BINOWN=	root
BINGRP=	operator
BINMODE=4550

.include <bsd.prog.mk>
