# $FreeBSD: src/lib/clang/libllvmasmprinter/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	llvmasmprinter

SRCDIR=	lib/CodeGen/AsmPrinter
SRCS=	AsmPrinter.cpp \
	AsmPrinterDwarf.cpp \
	AsmPrinterInlineAsm.cpp \
	DIE.cpp \
	DwarfDebug.cpp \
	DwarfException.cpp \
	OcamlGCPrinter.cpp

.include "../clang.lib.mk"
