# $FreeBSD: src/sbin/geom/class/multipath/Makefile,v 1.3 2010/12/15 23:24:34 obrien Exp $

.PATH: ${.CURDIR}/../../misc

GEOM_CLASS=	multipath

CFLAGS+=  -I${.CURDIR}/../../../../sys

.include <bsd.lib.mk>
