# $FreeBSD: src/lib/clang/libllvminstcombine/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvminstcombine

SRCDIR=	lib/Transforms/InstCombine
SRCS=	InstCombineAddSub.cpp InstCombineAndOrXor.cpp \
	InstCombineCalls.cpp InstCombineCasts.cpp \
	InstCombineCompares.cpp InstCombineLoadStoreAlloca.cpp \
	InstCombineMulDivRem.cpp InstCombinePHI.cpp \
	InstCombineSelect.cpp InstCombineShifts.cpp \
	InstCombineSimplifyDemanded.cpp InstCombineVectorOps.cpp \
	InstructionCombining.cpp

TGHDRS= Intrinsics

.include "../clang.lib.mk"
