# $FreeBSD: src/sbin/geom/class/virstor/Makefile,v 1.3 2010/12/16 00:00:28 obrien Exp $

.PATH: ${.CURDIR}/../../misc ${.CURDIR}/../../../../sys/geom/virstor

GEOM_CLASS=	virstor

SRCS+=	binstream.c
SRCS+=	g_virstor_md.c

.include <bsd.lib.mk>
