#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/smm/07.lpr/Makefile,v 1.1 2010/12/04 10:11:20 uqs Exp $

VOLUME=	smm/07.lpd
SRCS=	0.t 1.t 2.t 3.t 4.t 5.t 6.t 7.t
MACROS=	-ms
USE_TBL=

.include <bsd.doc.mk>
