# $FreeBSD: src/usr.sbin/sa/Makefile,v 1.13 2010/01/02 11:07:44 ed Exp $

.PATH: ${.CURDIR}/../../usr.bin/lastcomm

PROG=	sa
MAN=	sa.8
SRCS=	main.c db.c pdb.c usrdb.c readrec.c

.include <bsd.prog.mk>
