#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/usd/05.dc/Makefile,v 1.1 2010/01/22 23:19:48 delphij Exp $

VOLUME=	usd/05.dc
SRCS=	dc
MACROS=	-ms
SRCDIR=	${.CURDIR}/../../../../usr.bin/dc/USD.doc

.include <bsd.doc.mk>
