# $FreeBSD: src/usr.sbin/pkg_install/version/Makefile,v 1.18 2010/04/23 11:07:43 flz Exp $

PROG=	pkg_version
SRCS=	main.c perform.c

WFORMAT?=	1

test:
	sh ${.CURDIR}/test-pkg_version.sh

.include <bsd.prog.mk>
