# Makefile for ntpd.
# $FreeBSD: src/usr.sbin/ntp/Makefile,v 1.14 2009/12/15 14:59:58 roberto Exp $

SUBDIR=	libopts libntp libparse ntpd ntpdc ntpq ntpdate \
	ntptime ntp-keygen sntp
SUBDIR+=	doc

.include <bsd.subdir.mk>
