# $FreeBSD: src/lib/clang/libllvmarminfo/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmarminfo

SRCDIR=	lib/Target/ARM/TargetInfo/
INCDIR=	lib/Target/ARM
SRCS=	ARMTargetInfo.cpp

TGHDRS= ARMGenRegisterNames ARMGenInstrNames

.include "../clang.lib.mk"
