# $FreeBSD: src/lib/clang/libllvmarminfo/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	llvmarminfo

SRCDIR=	lib/Target/ARM/TargetInfo/
INCDIR=	lib/Target/ARM
SRCS=	ARMTargetInfo.cpp

TGHDRS= ARMGenInstrNames \
	ARMGenRegisterNames

.include "../clang.lib.mk"
