# $FreeBSD: src/lib/clang/libllvmarminfo/Makefile,v 1.3 2010/09/19 10:54:58 dim Exp $

LIB=	llvmarminfo

SRCDIR=	lib/Target/ARM/TargetInfo/
INCDIR=	lib/Target/ARM
SRCS=	ARMTargetInfo.cpp

TGHDRS=	ARMGenInstrNames \
	ARMGenRegisterNames

.include "../clang.lib.mk"
