#	$FreeBSD: src/tools/tools/ath/Makefile,v 1.13 2011/01/24 06:46:03 adrian Exp $

SUBDIR=	athdebug athdecode athkey athpoke athprom athrd athregs athstats ath_ee_v14_print ath_prom_read ath_ee_v4k_print

.include <bsd.subdir.mk>
