#	$FreeBSD: src/tools/tools/ath/Makefile,v 1.12 2011/01/22 23:44:56 adrian Exp $

SUBDIR=	athdebug athdecode athkey athpoke athprom athrd athregs athstats ath_ee_v14_print ath_prom_read

.include <bsd.subdir.mk>
