#
# $FreeBSD: src/tools/tools/ether_reflect/Makefile,v 1.2 2010/02/25 14:42:26 ru Exp $
#
# A Makefile that builds both the ether_reflect program and its manual page.

PROG=   ether_reflect
DPADD=	${LIBPCAP}
LDADD=	-lpcap

.include <bsd.prog.mk>
