# $FreeBSD: src/lib/clang/libllvmbitwriter/Makefile,v 1.3 2010/07/20 17:16:57 ed Exp $

LIB=	llvmbitwriter

SRCDIR=	lib/Bitcode/Writer
SRCS=	BitWriter.cpp \
	BitcodeWriter.cpp \
	BitcodeWriterPass.cpp \
	ValueEnumerator.cpp

.include "../clang.lib.mk"
