# $FreeBSD: src/lib/clang/libllvmbitwriter/Makefile,v 1.2 2010/06/15 17:08:03 ed Exp $

LIB=	llvmbitwriter

SRCDIR=	lib/Bitcode/Writer
SRCS=	BitcodeWriter.cpp BitcodeWriterPass.cpp \
	ValueEnumerator.cpp

.include "../clang.lib.mk"
