# $FreeBSD: src/lib/clang/libllvmbitwriter/Makefile,v 1.4 2010/09/20 16:43:17 dim Exp $

LIB=	llvmbitwriter

SRCDIR=	lib/Bitcode/Writer
SRCS=	BitcodeWriter.cpp \
	BitcodeWriterPass.cpp \
	ValueEnumerator.cpp

.include "../clang.lib.mk"
