
# $FreeBSD: src/kerberos5/lib/Makefile,v 1.11 2008/05/07 13:53:03 dfr Exp $

SUBDIR=	libasn1 libgssapi_krb5 libgssapi_ntlm libgssapi_spnego libhdb \
	libheimntlm libhx509 libkadm5clnt libkadm5srv libkafs5 libkrb5 \
	libroken libsl libvers

.include <bsd.subdir.mk>
