# $FreeBSD: src/lib/clang/libclangfrontend/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	clangfrontend

SRCDIR=	tools/clang/lib/Frontend
SRCS=	ASTConsumers.cpp \
	ASTMerge.cpp \
	ASTUnit.cpp \
	BoostConAction.cpp \
	CacheTokens.cpp \
	CompilerInstance.cpp \
	CompilerInvocation.cpp \
	DeclXML.cpp \
	DependencyFile.cpp \
	DiagChecker.cpp \
	DocumentXML.cpp \
	FrontendAction.cpp \
	FrontendActions.cpp \
	FrontendOptions.cpp \
	GeneratePCH.cpp \
	InitHeaderSearch.cpp \
	InitPreprocessor.cpp \
	LangStandards.cpp \
	PCHReader.cpp \
	PCHReaderDecl.cpp \
	PCHReaderStmt.cpp \
	PCHWriter.cpp \
	PCHWriterDecl.cpp \
	PCHWriterStmt.cpp \
	PrintParserCallbacks.cpp \
	PrintPreprocessedOutput.cpp \
	StmtXML.cpp \
	TextDiagnosticBuffer.cpp \
	TextDiagnosticPrinter.cpp \
	TypeXML.cpp \
	VerifyDiagnosticsClient.cpp \
	Warnings.cpp

TGHDRS=	AttrList \
	Attrs \
	CC1Options \
	DeclNodes \
	DiagnosticASTKinds \
	DiagnosticCommonKinds \
	DiagnosticDriverKinds \
	DiagnosticFrontendKinds \
	DiagnosticLexKinds \
	DiagnosticSemaKinds \
	StmtNodes

.include "../clang.lib.mk"
