# $FreeBSD: src/lib/clang/libllvmx86disassembler/Makefile,v 1.1 2010/09/20 16:43:17 dim Exp $

LIB=	llvmx86disassembler

SRCDIR=	lib/Target/X86/Disassembler
INCDIR=	lib/Target/X86
SRCS=	X86Disassembler.cpp

TGHDRS=	X86GenDisassemblerTables \
	X86GenEDInfo \
	X86GenRegisterNames

.include "../clang.lib.mk"
