#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.sbin/edquota/Makefile,v 1.10 2010/05/07 00:41:12 mckusick Exp $

PROG=	edquota
MAN=	edquota.8

CSTD=	gnu99
WARNS?=	4

DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
