# $FreeBSD: src/usr.sbin/mlxcontrol/Makefile,v 1.6 2010/01/02 11:07:44 ed Exp $

PROG=	mlxcontrol
MAN=	mlxcontrol.8
SRCS=	command.c config.c interface.c util.c

CFLAGS+= -I${.CURDIR}/../../sys

WARNS?=	2

.include <bsd.prog.mk>
