# $FreeBSD: src/lib/clang/libclangparse/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	clangparse

SRCDIR=	tools/clang/lib/Parse
SRCS=	AttributeList.cpp DeclSpec.cpp MinimalAction.cpp \
	ParseCXXInlineMethods.cpp ParseDecl.cpp ParseDeclCXX.cpp \
	ParseExpr.cpp ParseExprCXX.cpp ParseInit.cpp ParseObjc.cpp \
	ParsePragma.cpp ParseStmt.cpp ParseTemplate.cpp \
	ParseTentative.cpp Parser.cpp

TGHDRS=	DiagnosticCommonKinds DiagnosticParseKinds

.include "../clang.lib.mk"
