# $FreeBSD: src/lib/clang/libclangparse/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	clangparse

SRCDIR=	tools/clang/lib/Parse
SRCS=	AttributeList.cpp \
	DeclSpec.cpp \
	MinimalAction.cpp \
	ParseCXXInlineMethods.cpp \
	ParseDecl.cpp \
	ParseDeclCXX.cpp \
	ParseExpr.cpp \
	ParseExprCXX.cpp \
	ParseInit.cpp \
	ParseObjc.cpp \
	ParsePragma.cpp \
	ParseStmt.cpp \
	ParseTemplate.cpp \
	ParseTentative.cpp \
	Parser.cpp

TGHDRS=	DiagnosticCommonKinds \
	DiagnosticParseKinds

.include "../clang.lib.mk"
