# $FreeBSD: src/lib/clang/libllvmx86asmparser/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	llvmx86asmparser

SRCDIR=	lib/Target/X86/AsmParser
INCDIR=	lib/Target/X86
SRCS=	X86AsmLexer.cpp \
	X86AsmParser.cpp

TGHDRS= X86GenAsmMatcher \
	X86GenInstrNames \
	X86GenRegisterNames

.include "../clang.lib.mk"
