# $FreeBSD: src/lib/clang/libllvmx86asmparser/Makefile,v 1.3 2010/09/19 10:54:58 dim Exp $

LIB=	llvmx86asmparser

SRCDIR=	lib/Target/X86/AsmParser
INCDIR=	lib/Target/X86
SRCS=	X86AsmLexer.cpp \
	X86AsmParser.cpp

TGHDRS=	X86GenAsmMatcher \
	X86GenInstrNames \
	X86GenRegisterNames

.include "../clang.lib.mk"
