# $FreeBSD: src/lib/clang/libllvmx86asmparser/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmx86asmparser

SRCDIR=	lib/Target/X86/AsmParser
INCDIR=	lib/Target/X86
SRCS=	X86AsmParser.cpp X86AsmLexer.cpp

TGHDRS= X86GenRegisterNames X86GenInstrNames X86GenAsmMatcher

.include "../clang.lib.mk"
