# $FreeBSD: src/lib/clang/libllvmmipsasmprinter/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	llvmmipsasmprinter

SRCDIR=	lib/Target/Mips/AsmPrinter
INCDIR=	lib/Target/Mips
SRCS=	MipsAsmPrinter.cpp

TGHDRS=	MipsGenAsmWriter \
	MipsGenInstrNames \
	MipsGenRegisterInfo.h \
	MipsGenRegisterNames

.include "../clang.lib.mk"
