# $FreeBSD: src/lib/clang/libllvmmipsasmprinter/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmmipsasmprinter

SRCDIR=	lib/Target/Mips/AsmPrinter
INCDIR=	lib/Target/Mips
SRCS=	MipsAsmPrinter.cpp

TGHDRS=	MipsGenAsmWriter MipsGenInstrNames MipsGenRegisterInfo.h \
	MipsGenRegisterNames

.include "../clang.lib.mk"
