# $FreeBSD: src/cddl/lib/libumem/Makefile,v 1.4 2010/03/02 19:04:07 uqs Exp $

.PATH: ${.CURDIR}/../../../cddl/compat/opensolaris/lib/libumem

LIB=	umem
SRCS=	umem.c
WARNS?=	0
CFLAGS+= -I${.CURDIR}/../../../cddl/compat/opensolaris/lib/libumem

.include <bsd.lib.mk>
