# $FreeBSD: src/usr.bin/rpcgen/Makefile,v 1.9 2010/01/02 10:27:05 ed Exp $

PROG=	rpcgen
SRCS=	rpc_main.c  rpc_clntout.c rpc_cout.c rpc_hout.c rpc_parse.c \
	rpc_sample.c rpc_scan.c rpc_svcout.c rpc_tblout.c rpc_util.c

.include <bsd.prog.mk>
