#	@(#)Makefile	8.1 (Berkeley) 7/19/93
# $FreeBSD: src/usr.bin/rlogin/Makefile,v 1.29 2010/01/02 10:27:05 ed Exp $

PROG=	rlogin

BINOWN=	root
BINMODE=4555
PRECIOUSPROG=

WARNS?=	3

.include <bsd.prog.mk>
