# $FreeBSD: src/tools/tools/mwl/mwlstats/Makefile,v 1.1 2009/06/01 18:27:16 sam Exp $

PROG=	mwlstats
BINDIR=	/usr/local/bin
NO_MAN=

SRCS=	main.c statfoo.c mwlstats.c

.include <bsd.prog.mk>

CFLAGS+= -I.
