# $FreeBSD: src/usr.sbin/boot0cfg/Makefile,v 1.11 2010/02/26 09:41:16 ru Exp $

PROG=	boot0cfg
MAN=	boot0cfg.8

DPADD=	${LIBGEOM} ${LIBBSDXML} ${LIBSBUF}
LDADD=	-lgeom -lbsdxml -lsbuf

.include <bsd.prog.mk>
