# $FreeBSD: src/lib/clang/libllvmcore/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmcore

SRCDIR=	lib/VMCore
SRCS=	AsmWriter.cpp Attributes.cpp AutoUpgrade.cpp BasicBlock.cpp \
	ConstantFold.cpp Constants.cpp Core.cpp DebugLoc.cpp \
	Dominators.cpp Function.cpp GVMaterializer.cpp Globals.cpp \
	IRBuilder.cpp InlineAsm.cpp Instruction.cpp Instructions.cpp \
	IntrinsicInst.cpp LLVMContext.cpp LLVMContextImpl.cpp \
	LeakDetector.cpp Metadata.cpp Module.cpp Pass.cpp \
	PassManager.cpp PrintModulePass.cpp Type.cpp \
	TypeSymbolTable.cpp Use.cpp Value.cpp ValueSymbolTable.cpp \
	ValueTypes.cpp Verifier.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
