# $FreeBSD: src/lib/clang/libllvmcore/Makefile,v 1.2 2010/06/15 17:08:03 ed Exp $

LIB=	llvmcore

SRCDIR=	lib/VMCore
SRCS=	AsmWriter.cpp Attributes.cpp AutoUpgrade.cpp BasicBlock.cpp \
	ConstantFold.cpp Constants.cpp Core.cpp DebugLoc.cpp \
	Dominators.cpp Function.cpp Globals.cpp IRBuilder.cpp \
	InlineAsm.cpp Instruction.cpp Instructions.cpp \
	IntrinsicInst.cpp LLVMContext.cpp LLVMContextImpl.cpp \
	LeakDetector.cpp Metadata.cpp Module.cpp Pass.cpp \
	PassManager.cpp PrintModulePass.cpp Type.cpp \
	TypeSymbolTable.cpp Use.cpp Value.cpp ValueSymbolTable.cpp \
	ValueTypes.cpp Verifier.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
