# $FreeBSD: src/usr.sbin/lpr/Makefile,v 1.11 2010/12/04 10:11:20 uqs Exp $

SUBDIR=	common_source chkprintcap lp lpc lpd lpq lpr lprm lptest pac \
	filters filters.ru

# Questions/ideas for lpr & friends could also be sent to:
#	freebsd-print@bostonradio.org

.include <bsd.subdir.mk>
