# $FreeBSD: src/sys/modules/sysvipc/sysvsem/Makefile,v 1.6 2010/10/13 14:44:38 rpaulo Exp $

.PATH: ${.CURDIR}/../../../kern

KMOD=	sysvsem
SRCS=	sysv_sem.c opt_sysvipc.h opt_compat.h

.include <bsd.kmod.mk>
