#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: src/usr.sbin/route6d/Makefile,v 1.13 2010/01/02 11:07:44 ed Exp $

PROG=	route6d
MAN=	route6d.8

CFLAGS+= -DHAVE_POLL_H

WARNS?=	1

.include <bsd.prog.mk>
