# $FreeBSD: src/lib/clang/libllvmarmasmparser/Makefile,v 1.4 2010/09/20 16:43:17 dim Exp $

LIB=	llvmarmasmparser

SRCDIR=	lib/Target/ARM/AsmParser
INCDIR=	lib/Target/ARM
SRCS=	ARMAsmLexer.cpp \
	ARMAsmParser.cpp

TGHDRS=	ARMGenAsmMatcher \
	ARMGenInstrNames \
	ARMGenRegisterInfo.h \
	ARMGenRegisterNames

.include "../clang.lib.mk"
