# $FreeBSD: src/lib/clang/libllvmarmasmparser/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmarmasmparser

SRCDIR=	lib/Target/ARM/AsmParser
INCDIR=	lib/Target/ARM
SRCS=	ARMAsmParser.cpp ARMAsmLexer.cpp

TGHDRS= ARMGenRegisterInfo.h ARMGenRegisterNames ARMGenInstrNames

.include "../clang.lib.mk"
