# $FreeBSD: src/lib/clang/libllvmarmasmparser/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	llvmarmasmparser

SRCDIR=	lib/Target/ARM/AsmParser
INCDIR=	lib/Target/ARM
SRCS=	ARMAsmParser.cpp \
	ARMAsmLexer.cpp

TGHDRS= ARMGenInstrNames \
	ARMGenRegisterInfo.h \
	ARMGenRegisterNames

.include "../clang.lib.mk"
