# $FreeBSD: src/lib/clang/libclangbasic/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	clangbasic

SRCDIR=	tools/clang/lib/Basic
SRCS=	Builtins.cpp ConvertUTF.c Diagnostic.cpp FileManager.cpp \
	IdentifierTable.cpp SourceLocation.cpp SourceManager.cpp \
	TargetInfo.cpp Targets.cpp TokenKinds.cpp Version.cpp

TGHDRS=	DiagnosticASTKinds DiagnosticAnalysisKinds \
	DiagnosticCommonKinds DiagnosticDriverKinds \
	DiagnosticFrontendKinds DiagnosticGroups DiagnosticLexKinds \
	DiagnosticParseKinds DiagnosticSemaKinds

.include "../clang.lib.mk"
