# $FreeBSD: src/lib/clang/libclangbasic/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	clangbasic

SRCDIR=	tools/clang/lib/Basic
SRCS=	Builtins.cpp \
	ConvertUTF.c \
	Diagnostic.cpp \
	FileManager.cpp \
	IdentifierTable.cpp \
	SourceLocation.cpp \
	SourceManager.cpp \
	TargetInfo.cpp \
	Targets.cpp \
	TokenKinds.cpp \
	Version.cpp

TGHDRS=	AttrList \
	Attrs \
	DiagnosticASTKinds \
	DiagnosticAnalysisKinds \
	DiagnosticCommonKinds \
	DiagnosticDriverKinds \
	DiagnosticFrontendKinds \
	DiagnosticGroups \
	DiagnosticLexKinds \
	DiagnosticParseKinds \
	DiagnosticSemaKinds \
	arm_neon

.include "../clang.lib.mk"
