#	$NetBSD: Makefile,v 1.2 1998/07/12 20:40:45 augustss Exp $
#	FreeBSD $FreeBSD: src/usr.sbin/usbdevs/Makefile,v 1.11 2010/01/02 11:07:44 ed Exp $

PROG=	usbdevs
MAN=	usbdevs.8

.include <bsd.prog.mk>
