#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: src/games/fortune/strfile/Makefile,v 1.8 2010/02/15 14:32:00 uqs Exp $

PROG=	strfile
MAN=	strfile.8
MLINKS= strfile.8 unstr.8

.include <bsd.prog.mk>
