# $FreeBSD: src/usr.sbin/services_mkdb/Makefile,v 1.1 2010/04/04 08:38:14 ume Exp $

PROG=	services_mkdb
MAN=	services_mkdb.8
SRCS=	services_mkdb.c uniq.c

DPADD+=	${LIBUTIL}
LDADD+=	-lutil

.include <bsd.prog.mk>
