# $FreeBSD: src/usr.sbin/pc-sysinstall/backend/Makefile,v 1.1 2010/06/24 22:21:47 imp Exp $

FILES=	functions-bsdlabel.sh functions-cleanup.sh functions-disk.sh \
	functions-extractimage.sh functions-installcomponents.sh \
	functions-localize.sh functions-mountdisk.sh \
	functions-mountoptical.sh functions-networking.sh \
	functions-newfs.sh functions-parse.sh functions-runcommands.sh \
	functions-unmount.sh functions-upgrade.sh functions-users.sh \
	functions.sh parseconfig.sh startautoinstall.sh

FILESDIR=${SHAREDIR}/pc-sysinstall/backend
NO_OBJ=

.include <bsd.prog.mk>
