# $FreeBSD: src/tools/tools/netrate/tcpp/Makefile,v 1.2 2010/03/02 16:58:04 uqs Exp $

PROG=	tcpp
INCS=	tcpp.h
NO_MAN=	
SRCS=	tcpp.c tcpp_client.c tcpp_server.c tcpp_util.c
WARNS?=	3

.include <bsd.prog.mk>
