# $FreeBSD: src/lib/clang/libclanglex/Makefile,v 1.2 2010/07/20 17:16:57 ed Exp $

LIB=	clanglex

SRCDIR=	tools/clang/lib/Lex
SRCS=	HeaderMap.cpp \
	HeaderSearch.cpp \
	Lexer.cpp \
	LiteralSupport.cpp \
	MacroArgs.cpp \
	MacroInfo.cpp \
	PPCaching.cpp \
	PPDirectives.cpp \
	PPExpressions.cpp \
	PPLexerChange.cpp \
	PPMacroExpansion.cpp \
	PTHLexer.cpp \
	Pragma.cpp \
	PreprocessingRecord.cpp \
	Preprocessor.cpp \
	PreprocessorLexer.cpp \
	ScratchBuffer.cpp \
	TokenConcatenation.cpp \
	TokenLexer.cpp

TGHDRS=	DiagnosticCommonKinds \
	DiagnosticLexKinds

.include "../clang.lib.mk"
