#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: src/usr.bin/unifdef/Makefile,v 1.7 2010/01/02 10:27:05 ed Exp $

PROG=	unifdef
SCRIPTS=unifdefall.sh
MLINKS=	unifdef.1 unifdefall.1

.include <bsd.prog.mk>
