# $FreeBSD: src/lib/clang/libllvmtarget/Makefile,v 1.4 2010/09/20 16:43:17 dim Exp $

LIB=	llvmtarget

SRCDIR=	lib/Target
SRCS=	Mangler.cpp \
	SubtargetFeature.cpp \
	Target.cpp \
	TargetAsmLexer.cpp \
	TargetData.cpp \
	TargetELFWriterInfo.cpp \
	TargetFrameInfo.cpp \
	TargetInstrInfo.cpp \
	TargetLoweringObjectFile.cpp \
	TargetMachine.cpp \
	TargetRegisterInfo.cpp \
	TargetSubtarget.cpp

.include "../clang.lib.mk"
