# $FreeBSD: src/lib/clang/libllvmtarget/Makefile,v 1.3 2010/07/20 17:16:57 ed Exp $

LIB=	llvmtarget

SRCDIR=	lib/Target
SRCS=	Mangler.cpp \
	SubtargetFeature.cpp \
	Target.cpp \
	TargetAsmLexer.cpp \
	TargetData.cpp \
	TargetELFWriterInfo.cpp \
	TargetFrameInfo.cpp \
	TargetInstrInfo.cpp \
	TargetIntrinsicInfo.cpp \
	TargetLoweringObjectFile.cpp \
	TargetMachine.cpp \
	TargetRegisterInfo.cpp \
	TargetSubtarget.cpp

.include "../clang.lib.mk"
