# $FreeBSD: src/lib/clang/libllvmtarget/Makefile,v 1.2 2010/06/15 17:08:03 ed Exp $

LIB=	llvmtarget

SRCDIR=	lib/Target
SRCS=	Mangler.cpp SubtargetFeature.cpp Target.cpp TargetAsmLexer.cpp \
	TargetData.cpp TargetELFWriterInfo.cpp TargetFrameInfo.cpp \
	TargetInstrInfo.cpp TargetLoweringObjectFile.cpp \
	TargetMachine.cpp TargetRegisterInfo.cpp TargetSubtarget.cpp

.include "../clang.lib.mk"
