# $FreeBSD: src/sys/modules/sysvipc/sysvmsg/Makefile,v 1.6 2010/10/13 14:44:38 rpaulo Exp $

.PATH: ${.CURDIR}/../../../kern

KMOD=	sysvmsg
SRCS=	sysv_msg.c opt_sysvipc.h opt_compat.h

.include <bsd.kmod.mk>
