#	from: @(#)Makefile	5.5 (Berkeley) 5/11/90
# $FreeBSD: src/usr.sbin/rtprio/Makefile,v 1.9 2010/01/02 11:07:44 ed Exp $

PROG=	rtprio
LINKS=  ${BINDIR}/rtprio ${BINDIR}/idprio
MLINKS= rtprio.1 idprio.1

WARNS?=	2

.include <bsd.prog.mk>
