#	from: @(#)Makefile	8.1 (Berkeley) 6/4/93
# $FreeBSD: src/libexec/rbootd/Makefile,v 1.13 2010/01/02 09:50:19 ed Exp $

PROG=	rbootd
SRCS=	bpf.c conf.c parseconf.c rbootd.c rmpproto.c utils.c
MAN=	rbootd.8

WARNS?=	1
WFORMAT=0

.include <bsd.prog.mk>
