#	$OpenBSD: Makefile,v 1.1 1997/01/26 02:23:20 millert Exp $
# $FreeBSD: src/sbin/fsirand/Makefile,v 1.7 2010/05/14 14:26:49 uqs Exp $

PROG=	fsirand
MAN=	fsirand.8
WARNS?=	3
DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
