#	$ANA: Makefile,v 1.1.1.1 1996/09/25 21:12:57 wollman Exp $
# $FreeBSD: src/usr.sbin/pciconf/Makefile,v 1.11 2010/01/02 11:07:44 ed Exp $

PROG=	pciconf
SRCS=	pciconf.c cap.c
MAN=	pciconf.8

CFLAGS+= -I${.CURDIR}/../../sys

WARNS?=	3

.include <bsd.prog.mk>
