# $FreeBSD: src/lib/clang/libllvmmc/Makefile,v 1.2 2010/06/15 17:08:03 ed Exp $

LIB=	llvmmc

SRCDIR=	lib/MC
SRCS=	MCAsmInfo.cpp MCAsmInfoCOFF.cpp MCAsmInfoDarwin.cpp \
	MCAsmStreamer.cpp MCAssembler.cpp MCCodeEmitter.cpp \
	MCContext.cpp MCExpr.cpp MCInst.cpp MCInstPrinter.cpp \
	MCLoggingStreamer.cpp MCMachOStreamer.cpp MCNullStreamer.cpp \
	MCObjectWriter.cpp MCSection.cpp MCSectionCOFF.cpp \
	MCSectionELF.cpp MCSectionMachO.cpp MCStreamer.cpp \
	MCSymbol.cpp MachObjectWriter.cpp TargetAsmBackend.cpp

.include "../clang.lib.mk"
