# $FreeBSD: src/lib/clang/libllvmmc/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmmc

SRCDIR=	lib/MC
SRCS=	MCAsmInfo.cpp MCAsmInfoCOFF.cpp MCAsmInfoDarwin.cpp \
	MCAsmStreamer.cpp MCAssembler.cpp MCCodeEmitter.cpp \
	MCContext.cpp MCDisassembler.cpp MCExpr.cpp MCInst.cpp \
	MCInstPrinter.cpp MCLoggingStreamer.cpp MCMachOStreamer.cpp \
	MCNullStreamer.cpp MCObjectWriter.cpp MCSection.cpp \
	MCSectionCOFF.cpp MCSectionELF.cpp MCSectionMachO.cpp \
	MCStreamer.cpp MCSymbol.cpp MCValue.cpp MachObjectWriter.cpp \
	TargetAsmBackend.cpp

.include "../clang.lib.mk"
