#	@(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/usd/06.bc/Makefile,v 1.1 2010/01/22 23:19:48 delphij Exp $

VOLUME=	usd/06.bc
SRCS=	bc
MACROS=	-ms
SRCDIR=	${.CURDIR}/../../../../usr.bin/bc/USD.doc

.include <bsd.doc.mk>
