# $FreeBSD: src/lib/clang/libllvmbitreader/Makefile,v 1.5 2010/09/20 16:43:17 dim Exp $

LIB=	llvmbitreader

SRCDIR=	lib/Bitcode/Reader
SRCS=	BitcodeReader.cpp

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
