# $FreeBSD: src/lib/clang/libllvmbitreader/Makefile,v 1.3 2010/07/20 17:16:57 ed Exp $

LIB=	llvmbitreader

SRCDIR=	lib/Bitcode/Reader
SRCS=	BitReader.cpp \
	BitcodeReader.cpp

TGHDRS= Intrinsics

.include "../clang.lib.mk"
