# $FreeBSD: src/lib/clang/libllvmbitreader/Makefile,v 1.1 2010/06/09 19:32:20 rdivacky Exp $

LIB=	llvmbitreader

SRCDIR=	lib/Bitcode/Reader
SRCS=	BitReader.cpp BitcodeReader.cpp

TGHDRS= Intrinsics

.include "../clang.lib.mk"
