#	From: @(#)Makefile	1.6 (Berkeley) 6/8/93
# $FreeBSD: src/share/doc/papers/sysperf/Makefile,v 1.10 2011/01/26 19:39:31 uqs Exp $

VOLUME=		papers
DOC=		sysperf
SRCS=		0.t 1.t 2.t 3.t 4.t 5.t 6.t 7.t appendix.ms
EXTRA=		a1.t a2.t
MACROS=		-ms
USE_EQN=
USE_TBL=

.include <bsd.doc.mk>
